#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Automated project setup driven by design-spec.md.

Reads the design-spec.md configuration and runs the appropriate ingestion
steps based on the user's answers. This is the single entry point for both
the `vs` CLI and manual setup.

Runs scripts in-process via direct Python imports -- does NOT shell out to
`python scripts/...`. That makes setup safe to invoke from any cwd, against
any Python interpreter, regardless of whether the skill files were copied
into the workspace.

Usage:
    python scripts/setup.py --config ./design-spec.md
    python scripts/setup.py --config ./design-spec.md --dry-run
"""

# pylint: disable=line-too-long
# (log lines and error messages with config paths are intentionally long.)

import argparse
import logging
import pathlib
import sys
from typing import Any

# Allow imports from the script's own directory before pip install -e is run.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

# pylint: disable=wrong-import-position
import ingest_bigquery
import ingest_vertex_search
import validate_schema
from _paths import SAMPLE_PRODUCTS_CSV
from _setup_utils import load_config

# pylint: enable=wrong-import-position

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


# Mapping from design-spec.md YAML keys to the .env variables they populate.
# Each entry is `(yaml_key, env_key, default)`.
_DESIGN_SPEC_TO_ENV = [
    ("gcp_project_id", "GOOGLE_CLOUD_PROJECT", None),
    ("gcp_region", "VECTOR_SEARCH_LOCATION", None),
    ("gemini_model", "GEMINI_MODEL", None),
    ("embedding_model", "EMBEDDING_MODEL", None),
]


def _write_env_file(
    cfg: dict, env_path: pathlib.Path, collection_path: str | None = None
) -> None:
    """Write a `.env` file next to design-spec.md from the parsed config.

    This is what makes design-spec.md a Q-MODE-only artifact: after this
    runs, every downstream module reads its config from `.env` via
    scripts.config, not from design-spec.md.
    """
    lines = [
        "# Generated by scripts/setup.py from design-spec.md. Edit freely.\n"
    ]
    for yaml_key, env_key, default in _DESIGN_SPEC_TO_ENV:
        value = cfg.get(yaml_key) or default
        if value:
            lines.append(f"{env_key}={value}\n")
    if collection_path:
        lines.append(f"VECTOR_SEARCH_COLLECTION={collection_path}\n")
    env_path.write_text("".join(lines))
    logger.info("  Wrote %s (%d keys)", env_path, len(lines) - 1)


# Indirection layer so tests can monkeypatch these without touching the
# underlying scripts. Production: forwards to the real implementations.
def _validate_file(file_path, fields_level):
    return validate_schema.validate_file(file_path, fields_level)


def _run_bigquery_ingest(  # pylint: disable=too-many-arguments
    *, project_id, dataset_id, table_id, source, source_format, if_exists
):
    return ingest_bigquery.ingest(
        project_id=project_id,
        dataset_id=dataset_id,
        table_id=table_id,
        source=source,
        source_format=source_format,
        if_exists=if_exists,
    )


def _run_vertex_ingest(**kwargs):
    return ingest_vertex_search.ingest_pipeline(**kwargs)


def _resolve_data_source(cfg: dict[str, Any]) -> tuple[str | None, str]:
    """Resolve ``data_source`` from the spec into ``(source_path, format)``.

    Args:
        cfg: Parsed design-spec config dict.

    Returns:
        ``(source_path, format)`` where ``source_path`` is a local path or
        ``gs://`` URI and ``format`` is ``"csv"`` or ``"json"``. Returns
        ``(None, "")`` if the source is missing or broken so the caller
        can error out cleanly.
    """
    raw = (cfg.get("data_source") or "").strip()

    if raw.startswith("gs://"):
        return raw, _format_from_path(raw)

    if raw and raw not in ("default", "assets/sample-products.csv"):
        # User specified an explicit local path.
        if pathlib.Path(raw).exists():
            return raw, _format_from_path(raw)
        logger.error("\n  data_source '%s' does not exist.", raw)
        return None, ""

    # Default: the bundled sample inside the install dir.
    if SAMPLE_PRODUCTS_CSV.exists():
        return str(SAMPLE_PRODUCTS_CSV), "csv"

    logger.error("\n  Bundled sample not found at %s", SAMPLE_PRODUCTS_CSV)
    return None, ""


def _format_from_path(path: str) -> str:
    """Return ``"json"`` for ``.json``/``.jsonl`` paths, else ``"csv"``.

    Args:
        path: Data file path (local or gs:// URI).

    Returns:
        Either ``"json"`` or ``"csv"`` for the BigQuery loader.
    """
    return "json" if path.endswith((".json", ".jsonl")) else "csv"


def setup(config_path: str, dry_run: bool = False) -> bool:  # pylint: disable=too-many-locals
    """Run the full setup pipeline based on design-spec.md.

    Args:
        config_path: Path to ``design-spec.md`` with the user's config.
        dry_run: If True, log the pipeline shape without running ingest.

    Returns:
        True if every step succeeded; False if the data source couldn't
        be resolved or validation produced errors.
    """
    cfg = load_config(config_path)

    project_id = cfg.get("gcp_project_id", "")
    if not project_id:
        logger.error("gcp_project_id is required in design-spec.md")
        sys.exit(1)

    product_fields = cfg.get("product_fields", "Extended")
    dataset_id = cfg.get("dataset_id", "retail_skill_products")
    table_id = cfg.get("table_id", "products")
    catalog_size = cfg.get("catalog_size", "1K-50K")
    gcp_region = cfg.get("gcp_region", "us-central1")
    collection_id = cfg.get("collection_id", "retail-skill-products-collection")
    embedding_model = cfg.get("embedding_model", "gemini-embedding-001")
    raw_fields = cfg.get(
        "embedding_fields", "name, description, category, brand"
    )
    embedding_fields = [f.strip() for f in raw_fields.split(",")]

    logger.info("=" * 60)
    logger.info("SETUP PIPELINE (driven by design-spec.md)")
    logger.info("=" * 60)
    logger.info("  Project:      %s", project_id)
    logger.info("  Region:       %s", gcp_region)

    source, source_format = _resolve_data_source(cfg)
    if source is None:
        return False

    logger.info("  Data source:  %s", source)

    if dry_run:
        logger.info(
            "\n[dry-run] Would validate, ingest to BigQuery, then create Vector Search collection."
        )
        return True

    # Step A: validate.
    # validate_schema.load_records reads from the local filesystem only;
    # skip the schema-shape check for gs:// sources and let
    # ingest_bigquery.load_from_csv validate inline as it streams the file.
    if source.startswith("gs://"):
        logger.info(
            "\n  Skipping schema validation for gs:// source (validated inline during ingest)."
        )
    else:
        logger.info("\n  Validating sample data...")
        valid_count, errors = _validate_file(source, product_fields)
        if errors:
            logger.error(
                "  Validation produced %d errors. First 5:", len(errors)
            )
            for e in errors[:5]:
                logger.error("    %s", e)
            return False
        logger.info("  Validated %d records.", valid_count)

    # Step B: ingest to BigQuery (idempotent re-run via if_exists='skip')
    logger.info("\n  Ingesting into BigQuery...")
    _run_bigquery_ingest(
        project_id=project_id,
        dataset_id=dataset_id,
        table_id=table_id,
        source=source,
        source_format=source_format,
        if_exists="skip",
    )

    # Step C: create Vector Search collection + ingest
    logger.info("\n  Creating Vector Search collection...")
    collection_path = _run_vertex_ingest(
        project_id=project_id,
        location=gcp_region,
        dataset_id=dataset_id,
        table_id=table_id,
        collection_id=collection_id,
        embedding_model=embedding_model,
        embedding_fields=embedding_fields,
    )

    if catalog_size == "500K+":
        logger.info("\n  NOTE: Catalog size 500K+ detected.")
        logger.info(
            "  Consider using Dataflow for batch ingestion instead of direct inserts."
        )

    # Write .env next to design-spec.md so every downstream module
    # (agent.py, retrievers.py, ingest scripts) reads the same values via
    # scripts.config. Q-MODE users never touch .env by hand.
    env_path = pathlib.Path(config_path).resolve().parent / ".env"
    _write_env_file(cfg, env_path, collection_path=collection_path)

    logger.info("\n" + "=" * 60)
    logger.info("SETUP COMPLETE")
    logger.info("=" * 60)
    if collection_path:
        logger.info("  Collection path: %s", collection_path)
        logger.info("  Written to %s as VECTOR_SEARCH_COLLECTION.", env_path)
    return True


def main():
    """Parse CLI arguments and run the setup pipeline."""
    parser = argparse.ArgumentParser(
        description="Run setup pipeline from design-spec.md"
    )
    parser.add_argument(
        "--config", required=True, help="Path to design-spec.md"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would run without doing it",
    )

    args = parser.parse_args()
    ok = setup(args.config, args.dry_run)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
