#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Production exporter utility.

Copies backend scripts, UI static files, and writes container configurations
to target export folders for production Cloud Run deployments.
"""

import argparse
import logging
import os
import re
import shutil
import sys
import tomllib
from pathlib import Path

import yaml

try:
    from _setup_utils import load_config as _shared_load_config
except ImportError:
    _shared_load_config = None  # type: ignore[assignment]

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


def load_config(config_path: str) -> dict:
    """Load configuration from design-spec.md YAML frontmatter.

    Only closes the frontmatter on a line that is exactly `---` (with optional
    trailing whitespace). Naive `str.split("---", ...)` mis-splits on
    section-header comments like `# --- Required ---` inside the frontmatter.
    """
    path = Path(config_path)
    if not path.exists():
        logger.error(f"Config file not found at: {config_path}")
        return {}

    if _shared_load_config is not None:
        return _shared_load_config(config_path) or {}

    try:
        content = path.read_text()
        if content.startswith("---"):
            parts = re.split(r"^---\s*$", content, flags=re.MULTILINE)
            if len(parts) >= 3:
                return yaml.safe_load(parts[1]) or {}
        return yaml.safe_load(content) or {}
    except Exception as e:
        logger.error(f"Failed to parse config: {e}")
        return {}


def write_requirements(src_path: Path, dest_dir: Path) -> bool:
    """Generate the exported app's requirements.txt from pyproject.toml.

    Derived from the `serving` extra rather than shipped as a checked-in
    file, so the container's dependency list cannot drift from the recipe's.
    It drifted once already: python-dotenv was in `dependencies` but never
    mirrored into the template, and the exported app crashed on startup.
    """
    pyproject = src_path / "pyproject.toml"
    if not pyproject.exists():
        logger.error(f"pyproject.toml not found at: {pyproject}")
        return False

    with open(pyproject, "rb") as f:
        data = tomllib.load(f)

    extras = data.get("project", {}).get("optional-dependencies", {})
    serving = extras.get("serving")
    if not serving:
        logger.error(
            "No [project.optional-dependencies] 'serving' extra in "
            f"{pyproject}; the exported container would install nothing."
        )
        return False

    lines = [
        "# Generated by scripts/export_app.py -- do not edit by hand.",
        "# Source: [project.optional-dependencies] serving in the recipe's",
        "# pyproject.toml.",
        *serving,
    ]
    (dest_dir / "requirements.txt").write_text("\n".join(lines) + "\n")
    logger.info(f"Generated: requirements.txt ({len(serving)} dependencies)")
    return True


def export_app(config_path: str, skill_dir: str):
    """Package VTO sandbox into a standalone Cloud Run deployment folder."""
    config = load_config(config_path)
    if not config:
        logger.error("Empty or invalid design specification configuration.")
        return False

    project_id = config.get("gcp_project_id")
    if not project_id:
        logger.error("gcp_project_id is required in design-spec.md for export.")
        return False

    region = config.get("gcp_region", "us-west1")
    catalog_path = config.get("tryon_catalog_path", "catalog_images")
    output_bucket = (
        config.get("tryon_output_bucket") or f"{project_id}-tryon-output"
    )
    upload_bucket = (
        config.get("tryon_upload_bucket") or f"{project_id}-tryon-uploads"
    )
    model_name = config.get("tryon_model", "flash")

    # Destination directory path
    dest_val = config.get("export_directory") or "./vto-retail-app"
    dest_dir = Path(dest_val).resolve()
    logger.info(f"Exporting production-ready application to: {dest_dir}")

    dest_dir.mkdir(parents=True, exist_ok=True)
    ui_dest_dir = dest_dir / "ui"
    ui_dest_dir.mkdir(exist_ok=True)

    src_path = Path(skill_dir)

    # 1. Export UI assets
    ui_src_dir = src_path / "assets" / "ui"
    if ui_src_dir.exists():
        for f in ["index.html", "styles.css", "app.js"]:
            src_file = ui_src_dir / f
            if src_file.exists():
                shutil.copy2(src_file, ui_dest_dir / f)
                logger.info(f"Copied static asset: {f} -> {ui_dest_dir}")
    else:
        logger.error(f"UI source assets folder not found at: {ui_src_dir}")
        return False

    # 2. Export and Refactor Python source files
    scripts_src_dir = src_path / "scripts"
    # config.py is imported by every other module here, so omitting it makes
    # the exported container fail at startup on `from config import config`.
    py_files = [
        "config.py",
        "server.py",
        "tryon_processor.py",
        "tryon_agent.py",
        "scan_catalog.py",
        "setup_tryon.py",
    ]

    for f in py_files:
        src_file = scripts_src_dir / f
        if not src_file.exists():
            logger.warning(f"Python script not found: {src_file}")
            continue

        with open(src_file) as rfile:
            code = rfile.read()

        # Refactor imports from "scripts.X" to "X" for standalone root directory execution
        code = re.sub(
            r"from\s+scripts\.(?P<mod>\w+)\s+import",
            r"from \g<mod> import",
            code,
        )
        code = re.sub(
            r"import\s+scripts\.(?P<mod>\w+)", r"import \g<mod>", code
        )

        # In server.py, adjust the static asset mounts path
        if f == "server.py":
            # Change UI_DIR resolution to point directly to "./ui" in root
            code = code.replace(
                'UI_DIR = Path(__file__).resolve().parent.parent / "assets" / "ui"',
                'UI_DIR = Path(__file__).resolve().parent / "ui"',
            )

        dest_file = dest_dir / f
        with open(dest_file, "w") as wfile:
            wfile.write(code)
        # Preserve executability
        shutil.copymode(src_file, dest_file)
        logger.info(f"Exported python module: {f} -> {dest_dir}")

    # 3. Copy container / deploy templates from assets/export-template/,
    #    substituting {{TOKEN}} placeholders with values from design-spec.md.
    template_dir = src_path / "assets" / "export-template"
    if not template_dir.exists():
        logger.error(f"Export template directory not found at: {template_dir}")
        return False

    substitutions = {
        "{{PROJECT_ID}}": project_id,
        "{{REGION}}": region,
        "{{CATALOG_PATH}}": catalog_path,
        "{{OUTPUT_BUCKET}}": output_bucket,
        "{{UPLOAD_BUCKET}}": upload_bucket,
        "{{MODEL_NAME}}": model_name,
    }

    # Files marked executable in the export output. dict comprehension over
    # a name -> mode mapping keeps this obvious as new templates are added.
    executable_files = {"deploy_cloudrun.sh": 0o755}

    for template_file in sorted(template_dir.iterdir()):
        if not template_file.is_file():
            continue
        content = template_file.read_text()
        for token, value in substitutions.items():
            content = content.replace(token, value)
        dest_file = dest_dir / template_file.name
        dest_file.write_text(content)
        if template_file.name in executable_files:
            os.chmod(dest_file, executable_files[template_file.name])
        logger.info(f"Rendered: {template_file.name}")

    # 4. Generate the container's requirements.txt from the recipe's
    #    `serving` extra instead of copying a hand-maintained template.
    if not write_requirements(src_path, dest_dir):
        return False

    logger.info("EXPORT COMPLETED SUCCESSFULLY. Standalone source generated.")
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export virtual try-on app codebase for production"
    )
    parser.add_argument(
        "--config", required=True, help="Path to design-spec.md config"
    )
    parser.add_argument(
        "--skill-dir",
        required=True,
        help="Path to this skill installation directory",
    )
    args = parser.parse_args()

    success = export_app(args.config, args.skill_dir)
    if not success:
        sys.exit(1)
