#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Automated project setup for virtual try-on, driven by design-spec.md.

Reads design-spec.md, writes a `.env` file next to it so that subsequent
runs (server, agent, direct scripts) all share the same configuration,
then invokes setup_tryon.py to provision GCP resources.
"""

import argparse
import logging
import subprocess
import sys
from pathlib import Path

try:
    from _setup_utils import load_config, run_step
except ImportError:
    # Minimal fallback loader if _setup_utils isn't importable.
    def load_config(config_path: str) -> dict:
        import re

        import yaml

        try:
            content = Path(config_path).read_text()
            parts = re.split(r"^---\s*$", content, flags=re.MULTILINE)
            if len(parts) >= 3:
                return yaml.safe_load(parts[1]) or {}
        except Exception:  # noqa: S110
            pass
        return {}

    def run_step(description: str, cmd: list, dry_run: bool = False) -> bool:
        logger.info(description)
        if dry_run:
            logger.info(f"[DRY-RUN] Would run: {' '.join(cmd)}")
            return True
        res = subprocess.run(  # noqa: S603 -- setup script runs known command list
            cmd,
            check=False,
        )
        return res.returncode == 0


logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)


# Mapping from design-spec.md YAML keys to the .env variables they populate.
# Each entry is `(yaml_key, env_key, fallback_fn)`. `fallback_fn` receives
# the full cfg dict and returns a value when the YAML key is missing.
_DESIGN_SPEC_TO_ENV = [
    ("gcp_project_id", "GOOGLE_CLOUD_PROJECT", None),
    ("gcp_region", "GCP_REGION", None),
    ("tryon_model", "GEMINI_IMAGE_MODEL", None),
    (
        "tryon_output_bucket",
        "TRYON_OUTPUT_BUCKET",
        lambda c: (
            f"{c['gcp_project_id']}-tryon-output"
            if c.get("gcp_project_id")
            else None
        ),
    ),
    (
        "tryon_upload_bucket",
        "TRYON_UPLOAD_BUCKET",
        lambda c: (
            f"{c['gcp_project_id']}-tryon-uploads"
            if c.get("gcp_project_id")
            else None
        ),
    ),
    ("tryon_catalog_path", "TRYON_CATALOG_PATH", None),
]


def write_env_file(cfg: dict, env_path: Path) -> None:
    """Write a `.env` file next to design-spec.md from the parsed config.

    This is what makes design-spec.md a Q-MODE-only artifact: after this
    runs, every downstream module reads its config from `.env` via
    scripts.config, not from design-spec.md.
    """
    lines = [
        "# Generated by scripts/setup.py from design-spec.md. Edit freely.\n"
    ]
    for yaml_key, env_key, fallback in _DESIGN_SPEC_TO_ENV:
        value = cfg.get(yaml_key)
        if value is None and fallback is not None:
            value = fallback(cfg)
        if value:
            lines.append(f"{env_key}={value}\n")
    env_path.write_text("".join(lines))
    logger.info(f"  Wrote {env_path} ({len(lines) - 1} keys)")


def setup(config_path: str, dry_run: bool = False):
    """Run the virtual try-on setup pipeline based on design-spec.md."""
    cfg = load_config(config_path)

    project_id = cfg.get("gcp_project_id", "")
    if not project_id:
        logger.error("gcp_project_id is required in design-spec.md")
        sys.exit(1)

    tryon_categories = cfg.get("tryon_categories", ["Clothing"])
    tryon_mode = cfg.get("tryon_mode", "image_and_video")

    logger.info("=" * 60)
    logger.info("VIRTUAL TRY-ON SETUP (driven by design-spec.md)")
    logger.info("=" * 60)
    logger.info(f"  Project:            {project_id}")
    logger.info(f"  Region:             {cfg.get('gcp_region', '(default)')}")
    logger.info(f"  Categories:         {tryon_categories}")
    logger.info(f"  Try-On Mode:        {tryon_mode}")
    logger.info(f"  Image Model:        {cfg.get('tryon_model', '(default)')}")
    logger.info(
        f"  Output GCS Bucket:  {cfg.get('tryon_output_bucket') or f'{project_id}-tryon-output'}"
    )
    logger.info(
        f"  Upload GCS Bucket:  {cfg.get('tryon_upload_bucket') or f'{project_id}-tryon-uploads'}"
    )
    logger.info(
        f"  Catalog Path:       {cfg.get('tryon_catalog_path', 'catalog_images')}"
    )

    # Bridge design-spec.md into a workspace .env file. Every downstream
    # script (setup_tryon.py, server.py, tryon_agent.py, scan_catalog.py)
    # loads .env at import time via scripts.config.
    env_path = Path(config_path).resolve().parent / ".env"
    if not dry_run:
        write_env_file(cfg, env_path)
    else:
        logger.info(f"  [DRY-RUN] Would write {env_path}")

    setup_tryon_path = str(Path(__file__).resolve().parent / "setup_tryon.py")
    cmd = [sys.executable, setup_tryon_path, "--config", config_path]

    catalog_upload = cfg.get("tryon_catalog_upload", True)
    if catalog_upload is False:
        cmd.append("--no-upload")
    if tryon_mode in ("image_and_video", "video"):
        cmd.append("--video")

    ok = run_step(
        "\nRunning GCP resource setup & API verification...",
        cmd,
        dry_run,
    )

    export_dir = cfg.get("export_directory")
    if ok and export_dir:
        export_app_path = str(Path(__file__).resolve().parent / "export_app.py")
        export_cmd = [
            sys.executable,
            export_app_path,
            "--config",
            config_path,
            "--skill-dir",
            str(Path(__file__).resolve().parent.parent),
        ]
        ok = run_step(
            f"\nExporting standalone container application to: {export_dir}...",
            export_cmd,
            dry_run,
        )

    logger.info("\n" + "=" * 60)
    if ok:
        logger.info("VIRTUAL TRY-ON SETUP COMPLETED SUCCESSFULLY")
        logger.info("To start the agent run: adk web .")
        if export_dir:
            logger.info(f"Standalone application exported to: {export_dir}")
            logger.info(
                f"Navigate to '{export_dir}' and run 'deploy_cloudrun.sh' to deploy to Cloud Run."
            )
    else:
        logger.info("SETUP COMPLETED WITH ERRORS")
    logger.info("=" * 60)
    return ok


def main():
    parser = argparse.ArgumentParser(
        description="Run virtual try-on setup from design-spec.md"
    )
    parser.add_argument(
        "--config", required=True, help="Path to design-spec.md"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Show commands without running"
    )
    args = parser.parse_args()
    ok = setup(args.config, args.dry_run)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
